### PR TITLE
Use index.js as the package main file

### PR DESCRIPTION
**Pull request by ahuth**
This PR updates the package.json to use index.js as the package main file, instead of the compiled `dist` file.

After making this change, we can import this library in environments where we're using Webpack or other module systems, giving us direct access to the exported matchers.

### CODE REVIEW

**Comment by smacker** [comment]
I mainly agree with this change. But it will break environments without ES6 support. I don't think it's a big problem, but still, it's better to bump major version because it's breaking change. Do you mind to bump major number?

**Comment by ahuth** [comment]
Sure, no problem. Thanks for your responsiveness, and the major version number has been bumped.

**Comment by smacker** [comment]
Merged. Thank you!

**Comment by ahuth** [comment]
Thank you!

**Pull request merged**
